### ISSUE TITLE
Brillant

### ISSUE THREAD

**Issue by TeCoEd** [chncyhn/flappybird-qlearning-bot#1]
Excellent program thank you for sharing.  Is there a way to reset the rewards? I would like to see the 'learning', my Flappy Bird scored 246 on its first go!
Thanks

**Comment by chncyhn** [comment]
Hello Dan,

Thanks a lot for your kind words!

Yes, you can reset the Q-values by running the **initialize_qvalues.py** script. It resets all Q-values in the **qvalues.json** file to zero, so the learning would start from scratch.   

After you start running, every 25 games, the updated Q-values will be dumped to this json file. You can change the frequency of this by changing the _DUMPING_N_ variable in **bot.py**.

Also if you want to speed things up a little, you can change the _FPS_ global variable in **flappy.py** (which is normally set to 60 fps).

Cihan

**Comment by TeCoEd** [comment]
Hi Chan, 
Yes that worked very well, thank you.

**Comment by TeCoEd** [comment]
Any easy explanation how it measures the x and y pixel position, or is this the position from the pipe?

**Comment by chncyhn** [comment]
If you are talking about the **xdif** and **ydif** variables in the states - yes, they indicate the **horizontal** and **vertical** distance from the next pipe, respectively. They are calculated by subtracting the next pipe's left-top corner pixel positions from the bird's pixel positions.

`
bot.act(-playerx + myPipe['x'], - playery + myPipe['y'], playerVelY )`

You can see them calculated here in this function's first 2 arguments.

**Comment by TeCoEd** [comment]
Hi Cihan,
This make sense, so is the calculation of the next pipe position in real time or is this part of the Q array.
I am beginning to understand it!
Thanks

**Comment by chncyhn** [comment]
Hello Ted,

Yes, the calculation are in real time. The x- and y-distances are calculated in every tick of the game loop. After calculating these differences (and combining them with the current y-velocity of the bird) we get the current state of the bird, as (**xdif**, **ydif**, **yvel**). 

Then we look-up the respective Q[s,a] values of this state from the Q-array as you said, and choose the action _a_ with the higher Q-value. If value of  'jumping' is higher, the bird jumps; if not it does nothing. The bot makes this decision at every tick of the game loop.

Cihan
