### ISSUE TITLE
learn.py does not print out number of iterations and score

### ISSUE THREAD

**Issue by DenseLance** [chncyhn/flappybird-qlearning-bot#11]
When I ran learn.py, I realised the only thing that was printed is "Q-values updated on local file."
The code for learn.py, line 179-182, which does not work:
```
def showGameOverScreen(crashInfo):
    if VERBOSE:
        score = crashInfo['score']
        print(str(bot.gameCNT - 1) + " | " + str(score))
```
I would need to obtain the number of iterations and score quickly through learn.py, so please do help me to solve this problem as soon as possible. Thank you.

Also, line 35 of learn.py has a small mistake; it should be `--iter` instead of `iter` to pass the argument for iteration:

`parser.add_argument('--iter', type=int, default=5000, help='number of iterations to run')`

**Comment by chncyhn** [comment]
Hello @DenseLance, you can see there that you need to pass `--verbose` command line flag to be able to see the iterations. Can you try with this? 

I'm able to see the results per iteration:
![image](https://user-images.githubusercontent.com/18579419/67148947-af889400-f2a5-11e9-821d-5d2f9aed7711.png)

Thanks for pointing out the `--iter` issue. I'll push a fix soon, wanted to move some things around as well.

**Comment by chncyhn** [comment]
Pushed the fix.

**Comment by DenseLance** [comment]
I just started Python only recently, so I'm not sure what that means, so do forgive my ignorance.
It shows the following when I try to run learn.py with a default of 4 iterations.
![q-learning](https://user-images.githubusercontent.com/49511386/67154485-f3c07680-f32f-11e9-8599-d84944aa99bf.png)

My Q-values in the qvalues JSON file were updated after the code was ran. 

Thank you if you could help me solve this issue.


Edit: I figured out the mistake. For line 36, it should be `verbose` instead of `--verbose`
Result (these are after I reset the q-values):
![qvalue -1](https://user-images.githubusercontent.com/49511386/67154598-b78e1580-f331-11e9-8256-e11bb7861221.png)

Hence, 
For what I mentioned earlier, the code for lines 179-182 could be:

```
def showGameOverScreen(crashInfo):
    if VERBOSE:
        score = crashInfo['score']
        print(str(bot.gameCNT) + " | " + str(score))
```

This allows the iterations to start at 1 instead of 0 (it's neater this way to me, I guess. If you don't like it, it's also fine by me)

Thanks for helping!
